name: JMeter Performance Test

on:
  schedule:
    - cron: "0 8 * * *"   # codziennie o 10 i guess
  workflow_dispatch:          # możliwość ręcznego uruchomienia

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter test
        run: |
          jmeter -n -t JMeterGitHub.jmx -l results.jtl -Jsearch_paths=lib
          cat results.jtl
