name: JMeter Performance Test (Docker)

on:
  schedule:
    - cron: "0 8 * * *"   # codziennie o 10 i guess
  workflow_dispatch:          # możliwość ręcznego uruchomienia

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

     # - name: Install tools
      #  run: |
       #   sudo apt-get update
        #  sudo apt-get install -y wget tar

     # - name: Install JMeter 5.6.3
      #  run: |
       #   wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        #  tar -xzf apache-jmeter-5.6.3.tgz
         

      #- name: Run JMeter test
       # run: |
        #  ./apache-jmeter-5.6.3/bin/jmeter -n -t JMeterGitHub.jmx -l results.jtl -e -o report
         # cat results.jtl
         #cały czas na nowo tu było instalowane, ale robimy przez docker

      - name: Run Load Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/tests \
            justb4/jmeter:latest \
            -n -t /tests/[LoadTest]_GET_JsonPlaceHolder.jmx -l /tests/results.jtl -e -o /tests/report

      - name: Run Load Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/tests \
            justb4/jmeter:latest \
            -n -t /tests/[SpikeTest]_GET_JsonPlaceHolder.jmx -l /tests/results.jtl -e -o /tests/report

            # --- Nowy krok: publikacja raportu na GitHub Pages ---
      - name: Deploy JMeter report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3   # akcja do publikowania na gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # wbudowany token do pushowania
          publish_dir: ./report   # katalog z raportem JMeter
          publish_branch: gh-pages   # branch, na który ma wrzucać (utworzy się automatycznie)

      - name: Upload JMeter report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: report
